setwd("C:\\Users\\hp\\OneDrive\\Desktop\\data.frame")
getwd()

df = read.table("emp-data.txt",header = TRUE, sep =",")
str(df)
print(df)
head(df)
dftable=edit(df)
df$emp_sal=max(df$emp_sal)
print(emp_sal)
#sal=subset(df,emp_sal==max(emp_sal))
print(emp_sal)
df$join_date

library("readxl")
df1=read_excel("student.xlsx")
str(df1)
d1=data.frame(df$id,df$sidf$emp_desi)
d2=data.frame(df1$sid,df$name)
merge(d1,d2)
print(d1)
print(d2)
merge(d1,d2,by.x="df.id,by.y=id")
print('hello')
