#analyzing the csv file
emp_id=c(101,102,103)
emp_name=c('pink','sink','link')
emp_desi=c('clerk','manager','programmer')
emp_sal=c(40000,50000,80000)
employee=data.frame(emp_id,emp_name,emp_desi,emp_sal)
print(employee)
print(getwd())
setwd("C:\\Users\\hp\\OneDrive\\Desktop\\data.frame")
employee=read.csv('emp.csv')
print(employee)
print(is.data.frame(employee))
print(ncol(employee))
print(nrow(employee))
emptabe=edit(employee)#create tabe using edit method
print(employee)
employee=read.csv('emp.csv')
emp_sal=max(employee$emp_sal)
print(emp_sal)
sal=subset(employee,emp_sal==max(emp_sal))
print(sal)
info=subset(employee,emp_sal>50000 & emp_desi==manager)
print(info)
